package:
  name: openalpr
  version: 2.3.0 

source: 
  git_rev: v2.3.0
  git_url: https://github.com/openalpr/openalpr.git
  #fn: opencv-3.3.0.tar.gz
  #url: https://github.com/opencv/opencv/archive/3.3.0.tar.gz

build:
  number: 0

requirements:
  build:
     - python
     - opencv3
     - curl
     - openssl 1.0.*         [unix]
     - cmake
     - tesseract
     - leptonica
  run:
     - python

test:
  imports:
     - openalpr
